pipeline {
  agent any
  environment {
    WORKINGDIR = "gateway"
  }
  stages {
    stage('Configure Kubernetes Access') {
      steps {
              container('jnlp') {
                 sh """
                    apt update
                    apt install -y python3-pip golang
                    pip install awscli
                """
              }
        sh """
        aws eks update-kubeconfig --name continuous-testing --alias continuous-testing
        """
      }
    }
    stage('Running Test') {
      when {
        beforeAgent true
        allOf {
          branch 'overdrive-test'
        }
      }
      steps{
        dir(WORKINGDIR) {
          sh """
          pip3 install -U -e ".[dev]"
          coverage run -m pytest test/unit
          """
        }
      }
    }
  }

}