pipeline {
  agent any
  environment {
    WORKINGDIR = "gateway"
  }
  stages {
    stage('Configure Kubernetes Access') {
      steps {
        sh """
        aws eks update-kubeconfig --name continuous-testing --alias continuous-testing
        """
      }
    }
    stage('Install Dependencies') {
      when {
        beforeAgent true
        allOf {
          branch 'master'
        }
      }
      steps{
        dir(WORKINGDIR) {
          sh """
          pip3 install -U -e ".[dev]"
          """
        }
      }
    }
    stage('Running Test') {
      when {
        beforeAgent true
        allOf {
          branch 'master'
        }
      }
      steps{
        dir(WORKINGDIR) {
          sh """
          coverage run -m pytest test/unit
          """
        }
      }
    }
  }

}
