pipeline {
  agent any
  environment {
    WORKINGDIR = "infrastructure/repositories"
    TRIGGER = sh(
      script: "dirname \$(git diff --name-only --diff-filter=AMR HEAD^ ${WORKINGDIR}) 2>/dev/null || true",
      returnStdout: true
    )
  }
  stages {
    stage('Review Terraform Plan') {
      when {
        beforeAgent true
        allOf {
          changeRequest target: 'master'
          expression { TRIGGER != null }
        }
      }
      steps{
        dir("${WORKINGDIR}/module/test") {
          sh """
          go test
          """
        }
        dir(WORKINGDIR) {
          sh """
          terraform version
          terraform init
          terraform plan
          """
        }
      }
    }
    stage('Apply Terraform') {
      when {
        beforeAgent true
        allOf {
          branch 'master'
          expression { TRIGGER != null }
        }
      }
      steps{
        dir(WORKINGDIR) {
          sh """
          terraform init
          terraform apply
          """
        }
      }
    }
  }

}