pipeline {
  agent any
  environment {
    WORKINGDIR = "infrastructure/repositories"
  }
  stages {
    stage('Review Terraform Plan') {
      when {
        beforeAgent true
        allOf {
          changeRequest target: 'master'
          changeset "${WORKINGDIR}/**/*"
        }
      }
      steps{
        dir("${WORKINGDIR}/module/test") {
          sh """
          go test
          """
        }
        dir(WORKINGDIR) {
          sh """
          terraform version
          terraform init
          terraform plan
          """
        }
      }
    }
    stage('Apply Terraform') {
      when {
        beforeAgent true
        allOf {
          branch 'master'
          changeset "${WORKINGDIR}/**/*"
        }
      }
      steps{
        dir(WORKINGDIR) {
          sh """
          terraform init
          terraform apply
          """
        }
      }
    }
  }

}